export const INSPECTOR_SET_POSITION = 'INSPECTOR_SET_POSITION'
export const INSPECTOR_SET_POSITION_X = 'INSPECTOR_SET_POSITION_X'
export const INSPECTOR_SET_POSITION_Y = 'INSPECTOR_SET_POSITION_Y'
export const INSPECTOR_SET_DIMENSION = 'INSPECTOR_SET_DIMENSION'