export default {
  SIDEBAR_ADD_SCREEN: 'SIDEBAR_ADD_SCREEN',
  SIDEBAR_SET_MODE: 'SIDEBAR_SET_MODE',
  SIDEBAR_SET_SCREENS: 'SIDEBAR_SET_SCREENS',
  SIDEBAR_TOGGLE_COLLAPSED: 'SIDEBAR_TOGGLE_COLLAPSED',
}